name: Inline Message Workflow

on:
  push:
    branches: [master]

jobs:
  send-inline-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Send Inline Telegram Message
        uses: cbrgm/telegram-github-action@v1
        with:
          token: ${{ secrets.8205303925:AAGtxnGCAMqcsz4fJiUnMT_CIHzUocR3Zuo }}
          to: ${{ secrets.-1003172903974/110}}
          message: |
            ðŸš€ New Release Published!
            Release Name: ${{ github.event.release.name }}
            Tag: ${{ github.event.release.tag_name }}
            Actor: ${{ github.actor }}
            Repository: ${{ github.repository }}
            Check it out: ${{ github.event.release.html_url }}j
